
## OBTENER PRODUCTOS SE ESPERA PRODUCT [...]
GET http://localhost:3000/product

######
## OBTENER PRODUCTO POR ID, SE ESPERA PRODUCT
GET http://localhost:3000/product/5e791d5afa71545730247bd2

######
## CREAR PROUDUCTO, SE ESPERA PRODUCT
POST http://localhost:3000/product
Content-Type: application/json

{
  "name": "uvas",
  "description": "Este es una fruta",
  "price": 5
}
######
## EDITAR PRODUCTO, SE ESPERA PRODUCTO
PUT http://localhost:3000/product
Content-Type: application/json

{
  "id": "5e791d5afa71545730247bd2",
  "name": "melon"
}

######
## ELIMINAR PRODUCTO POR ID, SE ESPERA PRODUCTO
DELETE http://localhost:3000/product/5e791d5afa71545730247bd2