
## OBTENER PRODUCTOS SE ESPERA PRODUCT [...]
GET http://localhost:3000/product

######
## OBTENER PRODUCTO POR ID, SE ESPERA PRODUCT
GET http://localhost:3000/product/5e7911a6b958b73220fabae3

######
## CREAR PROUDUCTO, SE ESPERA PRODUCT
POST http://localhost:3000/product
Content-Type: application/json

{
  "name": "manzana",
  "description": "Este es una fruta",
  "price": 2
}
######
## EDITAR PRODUCTO, SE ESPERA PRODUCTO
PUT http://localhost:3000/product
Content-Type: application/json

{
  "id": "5e7911a6b958b73220fabae3",
  "price": 1
}

######
## ELIMINAR PRODUCTO POR ID, SE ESPERA PRODUCTO
DELETE http://localhost:3000/product/5e7911a6b958b73220fabae3