
GET http://localhost:3000/entries HTTP/1.1

#####

POST http://localhost:3000/entries HTTP/1.1
Content-Type: application/json


####

GET http://localhost:3000/entries/count HTTP/1.1

#####

GET http://localhost:3000/entries/5e7a3e648fa9855f20a548dc HTTP/1.1

#####

DELETE  http://localhost:3000/entries/5e7a3e6e8fa9855f20a548dd HTTP/1.1

#####

PUT  http://localhost:3000/entries HTTP/1.1
Content-Type: application/json

{
  "id": "5e7a3e648fa9855f20a548dc",
  "income": 1900
}
#####

POST http://localhost:3000/entries/test HTTP/1.1
Content-Type: application/json
